image: ubuntu:latest
before_script:


workflow:
  name: scribe-ci-test

stages:
    - docker-hook-image

.install_valint: &install_valint
  - apt update || apk update
  - apt install git curl -y || apk add git curl
  - curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/master/install.sh | sh -s -- -b /usr/local/bin
  - export PATH=$PATH:/usr/bin:/etc/docker

.init_signing_keys: &init_signing_keys
   - echo "Initiating signing keys"
  #  - export ATTEST_KEY=$(echo $ATTEST_KEY_B64 | base64 -d | tr -d '\r' )
  #  - export ATTEST_CERT=$(echo $ATTEST_CERT_B64 | base64 -d | tr -d '\r' )
  #  - export ATTEST_CA=$(echo $ATTEST_CA_B64 | base64 -d | tr -d '\r' )
   - export SIGNERS_KEY=$(echo $ATTEST_KEY_B64 | base64 -d | tr -d '\r' )
   - export SIGNERS_CERT=$(echo $ATTEST_CERT_B64 | base64 -d | tr -d '\r' )
   - export CA_CERT=$(echo $CA_CERT_B64 | base64 -d | tr -d '\r' )
   - printenv

docker-hook-image:
  tags: [ k8s-gitlab-runner ]
  stage: docker-hook-image
  variables:
    ENV: dev
    VALINT_SCRIBE_DISABLE: true
  extends: .basic-docker

.basic-docker:
    # tags: [ saas-linux-large-amd64 ]
    tags: [ k8s-gitlab-runner ]
    image: docker:latest
    variables:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375
    services:
      - docker:dind
    before_script:
      - apk update && apk add net-tools iproute2 || true
      - echo "Docker daemon is ready. Docker info:"
      - until docker info > /dev/null 2>&1; do
          echo "Docker daemon not available yet, waiting...";
          sleep 1;
        done
      - *init_signing_keys
      - *install_valint
    script:
      - valint verify busybox:latest
        --product-key das-scribe-poc-product
        --product-version 1.0.1
        --context-type gitlab
        --bom --provenance
        --ca env://CA_CERT
        --cert env://SIGNERS_CERT
        --key env://SIGNERS_KEY
        --format attest
        --rule slsa/l1-provenance-exists@v1
        --rule slsa/l2-provenance-authenticated@v1
        --verbose 2