image: ubuntu:latest
before_script:
  - apt update || apk update
  - apt install git curl -y || apk add git curl
  - curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/master/install.sh | sh -s -- -b /usr/local/bin
  - export PATH=$PATH:/usr/bin:/etc/docker

workflow:
  name: scribe-ci-test

stages:
    - docker-hook-image

.init_signing_keys: &init_signing_keys
   - echo "Initiating signing keys"
   - export ATTEST_KEY=$(echo $ATTEST_KEY_B64 | base64 -d | tr -d '\r' )
   - export ATTEST_CERT=$(echo $ATTEST_CERT_B64 | base64 -d | tr -d '\r' )
   - export ATTEST_CA=$(echo $ATTEST_CA_B64 | base64 -d | tr -d '\r' )
   - printenv
docker-hook-image:
  tags: [ k8s-gitlab-runner ]
  stage: docker-hook-image
  variables:
    ENV: dev
    VALINT_SCRIBE_DISABLE: true
  extends: .basic-docker

.basic-docker:
    # tags: [ saas-linux-large-amd64 ]
    tags: [ k8s-gitlab-runner ]
    image: docker:latest
    variables:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://docker:2375
    services:
      - docker:dind
    before_script:
      - apk update && apk add net-tools iproute2 || true
      - echo "Docker daemon is ready. Docker info:"
      - until docker info > /dev/null 2>&1; do
          echo "Docker daemon not available yet, waiting...";
          sleep 1;
        done
      - *init_signing_keys
    script:
      - docker pull busybox:latest
      - valint bom busybox:latest
        --product-key das-scribe-poc-product
        --product-version 1.0.1
        --context-type gitlab
        --format attest
        --ca ${CA_CERT}
        --cert ${SIGNERS_CERT}
        --key ${SIGNERS_KEY}
        -vv
      # - docker save -o busybox.tar busybox:latest
      # - valint bom docker-archive:busybox.tar
      #     --context-type gitlab
      #     --output-directory ./scribe/valint
      #     --output-file ./busybox.json
      #     -vv -f