trigger:
  branches:
    include:
    - master
    - SH-7283-simplification

variables:
  # dockerRegistryServiceConnection: '7f9dc28e-5551-43ee-891f-33bf61a995de'
  # imageRepository: 'usernamepipelinesjavascriptdocker'
  containerRegistry: 'scribe_dockerhub'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

# - name: SCRIBE_URL
#   value: https://api.staging.scribesecurity.com
# - name:  SCRIBE_LOGIN_URL
#   value: https://scribe-hub-staging.us.auth0.com
# - name: SCRIBE_AUDIENCE
#   value: api.staging.scribesecurity.com

jobs:

######################### PRE RELEASE / STAGING #########################
  - job: docker_hook_image
    displayName: docker_hook_image
    strategy:
      matrix:
        linux_agent:
          poolName: Mikey
          agentName: azure-runner-ubuntu

        # windows_agent:
        #   poolName: Mikey
        #   agentName: azure-runner-windows
    pool:
      name:  $(poolName)
      demands:
        - Agent.Name -equals  $(agentName)
  
    variables:
      - name: ENV
        value: dev
      - name: DEBUG
        value: "true"

    steps:

    - script: |
        sudo usermod -aG docker $USER
        newgrp docker
        groups
        printenv

    - script: echo Hello world
      displayName: Hello

    - script: id -nG
      displayName: see group info

    - script: id
      displayName: see info

    - script: ls -lh /var/run/
      displayName: see info


    # /usr/bin/docker build -f /home/azure-runner-ubuntu/myagent/_work/4/s/Dockerfile 
    #--label com.azure.dev.image.system.teamfoundationcollectionuri=https://dev.azure.com/***/ 
    #--label com.azure.dev.image.system.teamproject=Scribeproject 
    #--label com.azure.dev.image.build.repository.name=scribe-security/A-demo-webserver about:blank#blocked
    #--label com.azure.dev.image.build.sourceversion=b9174709042047b589c4cab552e7513fb0bddcb7 
    #--label com.azure.dev.image.build.repository.uri=https://github.com/scribe-security/A-demo-webserver 
    #--label com.azure.dev.image.build.sourcebranchname=SH-7283-simplification 
    #--label com.azure.dev.image.build.definitionname=scribe-security.A-demo-webserver 
    #--label com.azure.dev.image.build.buildnumber=20250130.7 
    #--label com.azure.dev.image.build.builduri=vstfs:///Build/Build/1183 
    #--label image.base.ref.name=node:20.13.1-slim -t test_mikey:1183 /home/azure-runner-ubuntu/myagent/_work/4/s

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: scribesecurity/test_mikey
        containerRegistry: $(containerRegistry)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
   
