trigger:
  branches:
    include:
    - master
    - SH-7283-simplification

variables:
  # dockerRegistryServiceConnection: '7f9dc28e-5551-43ee-891f-33bf61a995de'
  # imageRepository: 'usernamepipelinesjavascriptdocker'
  containerRegistry: 'scribe_dockerhub'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

# - name: SCRIBE_URL
#   value: https://api.staging.scribesecurity.com
# - name:  SCRIBE_LOGIN_URL
#   value: https://scribe-hub-staging.us.auth0.com
# - name: SCRIBE_AUDIENCE
#   value: api.staging.scribesecurity.com

jobs:

######################### PRE RELEASE / STAGING #########################
  - job: docker_hook_image
    displayName: docker_hook_image
    strategy:
      matrix:
        linux_agent:
          poolName: Mikey
          agentName: azure-runner-ubuntu

        # windows_agent:
        #   poolName: Mikey
        #   agentName: azure-runner-windows
    pool:
      name:  $(poolName)
      demands:
        - Agent.Name -equals  $(agentName)
  
    variables:
      - name: ENV
        value: dev
      - name: DEBUG
        value: "true"

    steps:

    - script: echo Hello world
      displayName: Hello


    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: test_mikey
        containerRegistry: $(containerRegistry)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
   
