name: Scribe Docker Policy Action
description: Verify compliance policies against evidence to ensure the integrity of supply chain.
author: Mikey Strauss
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  select:
    description: Select the policy to enforce [scout]
    required: true
  input:
    description: Input evidence to verify against policy
    required: false
  push-github-results:
    description: Push Results to github Security alerts
    required: false
  verify-only:
    description: Verify remote evidence against policy
    required: false
  args:
    description: Additional arguments to pass to the policy plugin
    required: false
  output-directory:
    description: Output directory for the policy plugin
    required: false
  product-key:
    description: Evidence Product key
    required: false
  product-version:
    description: Evidence Product version
    required: false
  output-file:
    description: Output file for the policy plugin
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Install Policy Plugin
      run: |
        # Ensure ~/.docker/cli-plugins/ exists in the PATH
        # export PATH=$PATH:~/.docker/cli-plugins/

        # Check if `docker` is installed and plugin is available
        if ! command -v docker > /dev/null; then
          echo "Docker is not installed or not available in PATH."
          exit 1
        fi

        docker --help || true
        echo "############### 1"
        POLICY_HELP=$(docker policy -h)
        echo "############### 2 $POLICY_HELP"
        docker --help | grep "*policy" || true
        
        # Attempt to use docker policy; ignore errors for this check
        if [ -z "$POLICY_HELP" ]; then
          echo "Docker policy plugin not found, installing..."
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
        else
          echo "Docker policy plugin already installed."
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
        fi

        docker --help || true
        echo "############### 1"
        docker policy -h || true
        echo "############### 2"
        POLICY_HELP=$(docker policy -h)
        echo "############### 3 $POLICY_HELP"

        # Verify plugin installation
        if [ -z "$POLICY_HELP" ]; then
          echo "Docker still does not recognize the policy plugin after installation."
          exit 1
        fi

    # - shell: bash
    #   name: Run Scribe Docker Policy
    #   run: |2-
    #     // Run `docker policy` command
    #     echo "docker policy ${{ inputs.target }} \
    #       --select ${{ inputs.select }} \
    #       -o attest \
    #       --product-version ${{ env.PRODUCT_VERSION }} \
    #       --output-directory output_evidence \
    #       --output-file scout.sarif.json.sig \
    #       --bundle-branch SH-6730-docker-plugin"

    
