name: Scribe Docker Policy Action
description: Verify compliance policies against evidence to ensure the integrity of supply chain.
author: Mikey Strauss
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  select:
    description: Select the policy to enforce [scout]
    required: true
  input:
    description: Input evidence to verify against policy
    required: false
  push-github-results:
    description: Push Results to github Security alerts
    required: false
  verify-only:
    description: Verify remote evidence against policy
    required: false
  args:
    description: Additional arguments to pass to the policy plugin
    required: false
  output-directory:
    description: Output directory for the policy plugin
    required: false
  product-key:
    description: Evidence Product key
    required: false
  product-version:
    description: Evidence Product version
    required: false
  output-file:
    description: Output file for the policy plugin
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Install Policy Plugin
      run: |
        set -x
        if ! command -v docker > /dev/null; then
          echo "Docker is not installed or not available in PATH."
          exit 1
        fi

        POLICY_HELP=$(docker policy -h | grep "valint" || true)
        echo "$POLICY_HELP"
        if [ -z "$POLICY_HELP" ]; then
          echo "Docker policy plugin not found, installing..."
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
        else
          echo "Docker policy plugin already installed."
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
        fi

        POLICY_HELP=$(docker policy -h | grep "valint" || true)
        echo "$POLICY_HELP"

        # Verify plugin installation
        if [ -z "$POLICY_HELP" ]; then
          echo "Docker still does not recognize the policy plugin after installation."
          exit 1
        else
          echo "Docker policy plugin installed successfully."
        fi

    # - shell: bash
    #   name: Run Scribe Docker Policy
    #   run: |2-
    #     // Run `docker policy` command
    #     echo "docker policy ${{ inputs.target }} \
    #       --select ${{ inputs.select }} \
    #       -o attest \
    #       --product-version ${{ env.PRODUCT_VERSION }} \
    #       --output-directory output_evidence \
    #       --output-file scout.sarif.json.sig \
    #       --bundle-branch SH-6730-docker-plugin"

    # - shell: bash
    #   name: Extract Sarif file
    #   run: |
    #     mkdir results
    #     cat  valint.sarif.json.sig | jq -r '.payload' | base64 -d | jq -r '.payload' | base64 --decode | jq '.predicate' | jq '.content' >  results/valint.sarif.json
    #     ls -lh
    #     cat results/valint.sarif.json


    # - name: Upload evidence
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: evidence
    #     path: |
    #       output_evidence
    #       valint.sarif.json
    #     retention-days: 1

    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: valint.sarif.json
    #     category: scout



    
