name: Scribe Docker Policy Action
description: Verify compliance policies against evidence to ensure the integrity of supply chain.
author: Mikey Strauss
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>]
    required: true
  select:
    description: Select the policy to enforce [scout]
    required: true
  input:
    description: Input evidence to verify against policy
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Install valint
      run: |2-
        // Check if `docker policy` is not installed [FIX]
        if ! command -v docker > /dev/null || ! docker policy --help > /dev/null 2>&1; then
           curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
        fi

    - shell: bash
      name: Run Scribe Docker Policy
      run: |2-
        // Run `docker policy` command
        echo "docker policy ${{ inputs.target }} \
          --select ${{ inputs.select }} \
          -o attest \
          --product-version ${{ env.PRODUCT_VERSION }} \
          --output-directory output_evidence \
          --output-file scout.sarif.json.sig \
          --bundle-branch SH-6730-docker-plugin"

    
