name: attest-slsa-test

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  PRODUCT_VERSION: 1.0.8
  IMAGE_NAME: star-generator
  APP_NAME: Sky-Mapper
  VALINT_BOM_AUTHOR_NAME: Guy-Chernobrov
  VALINT_BOM_AUTHOR_EMAIL: gc@scribesecurity.com
  VALINT_BOM_AUTHOR_PHONE: 052-9281309
  VALINT_BOM_SUPPLIER_NAME: Scribe-Security
  VALINT_BOM_SUPPLIER_URL: www.scribesecurity.com
  VALINT_BOM_SUPPLIER_EMAIL: info@scribesecurity.com
  VALINT_BOM_SUPPLIER_PHONE: 001-001-0011
  INTEGRATION_TEST: 15s
  GITHUB_RUN_NUM: ${{ github.run_number }}
  
  
on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: [main]

concurrency: 
  group: build-in-${{ github.ref }}
  cancel-in-progress: true

jobs:
  attest-slsa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
       
           
      - name: Create SBOM and SLSA provenance for SecOps-Scribe-${{ inputs.app_name }}
        env:
          # ATTEST_KEY: ${{ secrets.********* }}
          # ATTEST_CERT: ${{ secrets.********** }}
          # ATTEST_CA: ${{ vars.****** }}
          VERSION: ${{ github.event.inputs.version || format('1.1.{0}', github.run_number) || env.version }}

        id: scribe_scan_v1
        uses: scribe-security/action-slsa@master
        continue-on-error: true
        with:
          target: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE }}:${{ inputs.IMAGE_TAG }}
          bom: true
          provenance: true
          # attest-default: x509-env
          product-key: ${{ github.repository }}/${{ inputs.app_name }}
          product-version: ${{ github.event.inputs.version || format('1.1.{0}', github.run_number) || env.version }}
          format: attest
          external: "stage=SecOps-Scribe-${{ inputs.app_name }}"
          # initiative: slsa.l2@v2

 