name: Build-Helm-webserver-image
run-name: Build Webserver from ${{ github.ref_name }} branch
env:  
  VALINT_DISABLE_EVIDENCE_CACHE: false
  VALINT_SCRIBE_ENABLE: true 
  DOCKER_DRIVER: overlay2
  DEBUG: false
  SCRIBE_PRODUCT_NAME: "code_to_cloud"
  SCRIBE_PRODUCT_VERSION: "0.2"
  DOCKERHUB_USERNAME: scribesecurity
  JFROG_USER: gc@scribesecurity.com

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  Build-Webserver-Image:
    name: Build Webserver-Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Attest Source Code
        uses: scribe-security/action-bom@master
        with:
          target: git:.
          scribe-enable: true
          product-key:  ${{ env.SCRIBE_PRODUCT_NAME }}
          product-version: ${{env.SCRIBE_PRODUCT_VERSION}}   
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          format: attest
          label: "Flamingo"

      - name: Log in to Artifactory
        uses: docker/login-action@v3
        with:
          registry: https://scribesecuriy.jfrog.io
          username: ${{ env.JFROG_USER }}
          password: ${{ secrets.JFROG_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: scribesecuriy.jfrog.io/scribe-docker-public-local/sky-mapper:latest

      - name: Attest Docker Image
        uses: scribe-security/action-bom@master
        with:
           target: scribesecurity/sky-mapper:latest
           scribe-enable: true
           product-key:  ${{ env.SCRIBE_PRODUCT_NAME }}
           product-version: ${{env.SCRIBE_PRODUCT_VERSION}}   
           scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
           format: attest
           label: "Flamingo"




