name: Build-webserver-image-ECR
run-name: Build Webserver from ${{ github.ref_name }} branch

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  Build-Webserver-Image:
    name: Build Webserver-Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: scribesecurity/sky-mapper:latest