name: collect-evidence-trigger
  
on:
  workflow_dispatch:
  pull_request:

concurrency: 
  group: build-in-${{ github.ref }}
  cancel-in-progress: true

jobs:
  evidence-collector:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # actions: read
      # security-events: write
      # id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TRIGGER_PAT }}
          repository: scribe-security/complaince
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'