name: docker-hook-check

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  PRODUCT_VERSION: 1.0.8
  IMAGE_NAME: star-generator
  APP_NAME: Sky-Mapper
  VALINT_BOM_AUTHOR_NAME: Guy-Chernobrov
  VALINT_BOM_AUTHOR_EMAIL: gc@scribesecurity.com
  VALINT_BOM_AUTHOR_PHONE: 052-9281309
  VALINT_BOM_SUPPLIER_NAME: Scribe-Security
  VALINT_BOM_SUPPLIER_URL: www.scribesecurity.com
  VALINT_BOM_SUPPLIER_EMAIL: info@scribesecurity.com
  VALINT_BOM_SUPPLIER_PHONE: 001-001-0011
  INTEGRATION_TEST: 15s
  GITHUB_RUN_NUM: ${{ github.run_number }}
  
  
on:
  workflow_dispatch:
  pull_request:
#  push:
#    branches: [main]

concurrency: 
  group: build-in-${{ github.ref }}
  cancel-in-progress: true

jobs:

  docker-hook-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # only required for workflows in private repositories
      actions: read
      security-events: write
      id-token: write
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Valint Docker hooks
        uses: ./.github/actions/docker-hook-install

      - run: |
          alias

      - run: |
          docker --help
          
      - run: |

      - shell: bash
        run: |
          export rc=/tmp/docker-alias
          echo 'shopt -s expand_aliases' > $rc
          ls -lh /tmp
          echo 'alias docker="$HOME/.docker/cli-plugins/docker-policy-hook" ' >> $rc
          source  $rc
          DEBUG=true docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}

      # - run: |
      #     ls -la ${HOME}/.bashrc || true
      #     ls -la ${HOME}/.zshrc || true
      #     echo $PATH

      # - run: |
      #     DEBUG=true docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}


      #     ls -la $HOME/.docker/cli-plugins/
      #     DEBUG=true docker build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}
      #     ls -la $HOME/.cache/docker-policy/ || true

      # - run: |
      #     $HOME/docker/cli-plugins/docker-policy-hook  build . -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}


      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: false
      #     tags: ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}
      #     load: true
