name: docker-plugin-check

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  PRODUCT_VERSION: 1.0.8
  IMAGE_NAME: star-generator
  APP_NAME: Sky-Mapper
  VALINT_BOM_AUTHOR_NAME: Guy-Chernobrov
  VALINT_BOM_AUTHOR_EMAIL: gc@scribesecurity.com
  VALINT_BOM_AUTHOR_PHONE: 052-9281309
  VALINT_BOM_SUPPLIER_NAME: Scribe-Security
  VALINT_BOM_SUPPLIER_URL: www.scribesecurity.com
  VALINT_BOM_SUPPLIER_EMAIL: info@scribesecurity.com
  VALINT_BOM_SUPPLIER_PHONE: 001-001-0011
  INTEGRATION_TEST: 15s
  GITHUB_RUN_NUM: ${{ github.run_number }}
  
  
on:
  workflow_dispatch:
  pull_request:
#  push:
#    branches: [main]

concurrency: 
  group: build-in-${{ github.ref }}
  cancel-in-progress: true

jobs:
  policy-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}
           
      - name: Install Scribe Docker Plugin
        run: |
          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh -s -- -b SH-6730-docker-plugin -d -x
          docker --help
          ls -lha $HOME
          ls -lh $HOME/.docker || true
          ls -lh $HOME/.docker/cli-plugins || true

      - uses: aquasecurity/trivy-action@0.28.0
        name: Run Trivy
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}
          format: 'sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-report.sarif.json'
          # severity: 'CRITICAL,HIGH'

      - name: Run Scribe Docker Plugin
        run: |
          docker policy ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}} \
           --select scout \
           -o attest \
           --input-evidence trivy:trivy-report.sarif.json \
           --product-version ${{ env.PRODUCT_VERSION }} \
           --output-directory output_evidence \
           --bundle-branch SH-6730-docker-plugin

  # policy-docker-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     id-token: write
  #   steps:
      
  #     - name: Install Scribe Docker Plugin
  #       run: |
  #         curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/SH-6730-docker-plugin/docker-cli-plugin/install.sh | sh
  #         docker -h

  #     - name: Run Scribe Docker Plugin
  #       run: |
  #         docker policy ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:1.1.${{env.GITHUB_RUN_NUM}}
