name: Build-webserver-image-single-command
run-name: Build Webserver from ${{ github.ref_name }} branch
env:  
  VALINT_DISABLE_EVIDENCE_CACHE: false
  VALINT_SCRIBE_ENABLE: true 
  DOCKER_DRIVER: overlay2
  DEBUG: false
  SCRIBE_PRODUCT_NAME: "code_to_cloud"
  SCRIBE_PRODUCT_VERSION: "0.7.1"
  DOCKERHUB_USERNAME: scribesecurity
  JFROG_USER: gc@scribesecurity.com

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  Build-Webserver-Image:
    name: Build Webserver-Image
    runs-on: ubuntu-latest
    steps:
      - name: Verify Source Code (no checkout)
        uses: scribe-security/action-verify@master
        with:
           product-key:  ${{ env.SCRIBE_PRODUCT_NAME }}
           product-version: ${{env.SCRIBE_PRODUCT_VERSION}}   
           scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
           format: attest
           label: "Flamingo-source-test"
           all-evidence: true
           initiative: verify-fresh-sbom.yaml

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Attest Source Code
        uses: scribe-security/action-bom@master
        with:
          target: git:.
          scribe-enable: true
          product-key:  ${{ env.SCRIBE_PRODUCT_NAME }}
          product-version: ${{env.SCRIBE_PRODUCT_VERSION}}   
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          format: attest
          label: "Flamingo-source-test"

      - name: Verify Source Code
        uses: scribe-security/action-verify@master
        with:
           target: git:.
           product-key:  ${{ env.SCRIBE_PRODUCT_NAME }}
           product-version: ${{env.SCRIBE_PRODUCT_VERSION}}   
           scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
           format: attest
           label: "Flamingo-source-test"
           initiative: verify-fresh-sbom.yaml
