


- name: Verify SLSA 3
        uses: scribe-security/action-verify@master
        env:
          ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
          ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
          ATTEST_CA: ${{ secrets.ATTEST_CA }}
        with:
          scribe-enable: true
          product-key:  Star-Generator
          product-version: "v0.0.1-discovery-demo"
          attest-default: x509-env
          # scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.VALINT_SCRIBE_AUTH_CLIENT_SECRET_DEV_MIKEY }}
          format: attest
          config: .valint.yaml
          policy: slsa3-policy.yaml
          rule-args: RepoAsset=asset=scribe-security__A-demo-webserver_
          git-branch: SLSA-3-Compliance
          skip-bundle: false
          scribe-url: https://api.dev.scribesecurity.com
